version: '2.1'
services:

  config-server:
#    environment:
    image: saas-kss/config-server
#    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  eureka-registry:
    image: saas-kss/eureka--registry
#    restart: always
    ports:
      - 8761:8761
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  zuul-gateway:
    image: saas-kss/zuul-gateway
#    restart: always
#    depends_on:
#      config:
#        condition: service_healthy
    ports:
      - 80:4000
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  data-import-service:
    image: saas-kss/data-import-service
#    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
