version: '2.1'
services:

  config-server:
#    environment:
    image: saas-kss_config-server
#    restart: always
    ports:
      - 8888:8888
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    dns:
      - 8.8.8.8
    extra_hosts:
      - "config-server:${CONFIG_SERVER}"

  eureka-registry:
    image: saas-kss_eureka-registry
#    restart: always
    depends_on:
      - config-server
    links:
      - config-server
    ports:
      - 8761:8761
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    dns:
      - 8.8.8.8
    extra_hosts:
      - "config-server:${CONFIG_SERVER}"
      - "eureka-registry:${EUREKA_REGISTRY}"

  zuul-gateway:
    image: saas-kss_zuul-gateway
    depends_on:
      - config-server
      - eureka-registry
    links:
      - config-server
      - eureka-registry
    ports:
      - 80:4000
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    dns:
      - 8.8.8.8
    extra_hosts:
      - "config-server:${CONFIG_SERVER}"
      - "eureka-registry:${EUREKA_REGISTRY}"

  data-import-service:
    image: saas-kss_data-import-service
#    restart: always
    depends_on:
      - config-server
      - eureka-registry
    links:
      - config-server
      - eureka-registry
    ports:
      - 6000:6000
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    dns:
      - 8.8.8.8
    extra_hosts:
      - "config-server:${CONFIG_SERVER}"
      - "eureka-registry:${EUREKA_REGISTRY}"