version: '3'
services:

  config-server:
    build: config-server
    ports:
      - 8888:8888

  eureka-registry:
    build: eureka-registry
    ports:
      - 8761:8761

  zuul-gateway:
    build: zuul-gateway

  data-import-service:
    build: data-import-service
    ports:
      - 8000:8000
