version: '3'
services:

  config-server:
#    environment:
    image: saas-kss_config-server
#    restart: always
    ports:
      - 8888:8888
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    networks:
      - saas-kss-nw

  eureka-registry:
    image: saas-kss_eureka-registry
#    restart: always
    depends_on:
      - config-server
    ports:
      - 8761:8761
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    networks:
      - saas-kss-nw

  arangodb:
    image: arangodb:3.4.7
    ports:
      - 8529:8529
    networks:
      - saas-kss-nw
    volumes:
      - /data/arangodb:/var/lib/arangodb3

  zuul-gateway:
    image: saas-kss_zuul-gateway
    depends_on:
      - config-server
      - eureka-registry
    ports:
      - 80:4000
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    networks:
      - saas-kss-nw

  data-import-service:
    image: saas-kss_data-import-service
#    restart: always
    depends_on:
      - config-server
      - eureka-registry
      - arangodb
    ports:
      - 8000:8000
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    networks:
      - saas-kss-nw

networks:
  saas-kss-nw: