server:
  servlet:
    context-path: /data-import-service
  port: 8000

# arangodb
spring:
  data:
    arangodb:
      database: test
      user: root
      password: root123
      hosts: arangodb:8529