zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  routes:
    data-import-service:
        path: /data-import-service/**
        serviceId: data-import-service
        stripPrefix: false
        sensitiveHeaders:

server:
  port: 4000

spring:
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0
  zipkin:
    sender:
      type: web
    base-url: http://zipkin:9411